version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ccm_user
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: ccm_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ccm_user"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: "postgresql://ccm_user:change_me@db:5432/ccm_db?schema=public"
      SUPABASE_URL: ""
      SUPABASE_SERVICE_ROLE_KEY: ""
      PRISMA_MIGRATE: "true"
      # FRONTEND_URL utilisé par le backend si besoin (ex: pour CORS / cookies)
      FRONTEND_URL: "http://collierscolliersmaison.be"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      # URL que le code frontend utilise pour appeler l'API (public)
      VITE_API_URL: "http://57.129.139.107:5000"

volumes:
  pgdata: