version = "3"

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm install && node server-http.js"
healthcheckPath = "/"
healthcheckTimeout = 300

[variables]
NODE_ENV = "production"