version: "3"

build:
  builder: nixpacks

deploy:
  startCommand: node server-supabase.js
  healthcheckPath: /
  healthcheckTimeout: 300
  restartPolicyType: on-failure

variables:
  NODE_ENV: production
